substitutions:
  _REGION: europe-west1
  _SERVICE_NAME: carder-reco-api

steps:
  # Étape 1 - Build de l'image Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME', '.']

  # Étape 2 - Push de l'image dans Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME']

  # Étape 3 - Déploiement sur Cloud Run avec secret monté
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      [
        'gcloud', 'run', 'deploy', '$_SERVICE_NAME',
        '--image', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME',
        '--region', '$_REGION',
        '--platform', 'managed',
        '--memory', '1Gi',
        '--allow-unauthenticated',
        "--update-secrets=GOOGLE_APPLICATION_CREDENTIALS=firebase-service-account-key:latest"
      ]
